# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCall' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TestCall
pod 'Snapcall_Framework', {:git => 'https://github.com/snapcall/snapcall_sdk_ios.git', :tag => '5.4.3'}

  target 'TestCallTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestCall-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestCall-tvOS

  target 'TestCall-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
