# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNSnapcallReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

use_frameworks!
	#pod 'React.Framework'
	pod 'Snapcall_Framework', :git => 'https://snapcall@bitbucket.org/seampl/framework_snapcall_ios.git',:branch => 'sandbox'
  # Pods for RNSnapcallReact

end
